services:
  app:
    build: .
    tty: true
    ports: 
      - 3001:3001
      - 3030:3030
    volumes:
      - ..:/app
      - /app/node_modules
    depends_on:
      - db
    
  db:
    build:
      context: "."
      dockerfile: "db.Dockerfile"
    ports:
      - 3306:3306
      


